#ANSI esqape
#disable with -E option
#https://en.wikipedia.org/wiki/ANSI_escape_code
SGI_NORMAL='\e[0m'
SGI_INVERT='\e[1;7m'
#SGI_BLINK='\e[6m'
SGI_LIGHTBLUE_BLACK='\e[1;34m'
SGI_BRIGHTRED_BLACK='\e[1;31m'
SGI_LIMIT_LIVEDATA=${SGI_LIMIT_LIVEDATA:=$SGI_INVERT}
SGI_LIMIT_LIVEDATA_OUTTEMP_LOW=${SGI_LIMIT_LIVEDATA_OUTTEMP_LOW:=$SGI_LIGHTBLUE_BLACK}
SGI_LIMIT_LIVEDATA_OUTTEMP_HIGH=${SGI_LIMIT_LIVEDATA_OUTTEMP_HIGH:=$SGI_BRIGHTRED_BLACK}
SGI_LIMIT_LIVEDATA_INTEMP_LOW=${SGI_LIMIT_LIVEDATA_INTEMP_LOW:=$SGI_LIGHTBLUE_BLACK}
SGI_LIMIT_LIVEDATA_INTEMP_HIGH=${SGI_LIMIT_LIVEDATA_INTEMP_HIGH:=$SGI_BRIGHTRED_BLACK}


SGI_BATTERY_LOW=${SGI_BATTERY_LOW:=$SGI_BRIGHTRED_BLACK}
SGI_LEAK=${SGI_LEAK:="\a"$SGI_BRIGHTRED_BLACK} # add alert/bell \a if leakage detected

TERM_ANSI_ESCAPE=${TERM_ANSI_ESCAPE:=1}

#Limits for triggering of ansi escape highlights
LIMIT_LIVEDATA_WIND=${LIMIT_LIVEDATA_WIND:=80}  # 8 m/s - set param if value unset/null
LIMIT_LIVEDATA_RAINRATE=${LIMIT_LIVEDATA_RAINRATE:=10} # 1.0 mm/h - scale x10
LIMIT_LIVEDATA_RAINHOUR=${LIMIT_LIVEDATA_RAINHOUR:=10}
LIMIT_LIVEDATA_RAINDAY=${LIMIT_LIVEDATA_RAINDAILY:=30} # 3.0 mm
LIMIT_LIVEDATA_RAINEVENT=${LIMIT_LIVEDATA_RAINEVENT:=30}
LIMIT_LIVEDATA_RELBARO_LOW=${LIMIT_LIVEDATA_BAROREL_LOW:=9900} # 990 hpa - scale x10
LIMIT_LIVEDATA_OUTTEMP_LOW=${LIMIT_LIVEDATA_OUTTEMP_LOW:=-10} # -1.0 - scale x10
LIMIT_LIVEDATA_OUTTEMP_HIGH=${LIMIT_LIVEDATA_OUTTEMP_HIGH:=170} # 17.0 - scale x10
LIMIT_LIVEDATA_INTEMP_LOW=${LIMIT_LIVEDATA_INTEMP_LOW:=200} 
LIMIT_LIVEDATA_INTEMP_HIGH=${LIMIT_LIVEDATA_INTEMP_HIGH:=230} 
