#!/usr/bin/dash
#ANSI escape
#disable with -E option
#https://en.wikipedia.org/wiki/ANSI_escape_code
CSI='\e[' # control sequence introducer
SGI_NORMAL=0
SGI_BOLD=1
SGI_BLINK=6
SGI_INVERSE=7
SGI_FOREGROUND_COLOR=38
SGI_BACKGROUND_COLOR=48

SGI_FOREGC="$SGI_FOREGROUND_COLOR;5;"
SGI_BACKGC="$SGI_BACKGROUND_COLOR;5;"
SGI_FOREGC_24BIT="$SGI_FOREGROUND_COLOR;2;"
SGI_BACKGC_24BIT="$SGI_BACKGROUND_COLOR;2;"
ANSIESC_SGI_NORMAL="$CSI${SGI_NORMAL}m"
ANSIESC_SGI_INVERT="$CSI${SGI_INVERSE}m"
ANSIESC_SGI_BOLD_INVERT="$CSI$SGI_BOLD;${SGI_INVERSE}m"
ANSIESC_SGI_BOLD="$CSI${SGI_BOLD}m"

#Colors 8-bit
SGI_COLOR_BLACK=0
SGI_COLOR_RED=1
SGI_COLOR_GREEN=2
SGI_COLOR_YELLOW=3
SGI_COLOR_BLUE=4
SGI_COLOR_MAGENTA=5
SGI_COLOR_CYAN=6
SGI_COLOR_WHITE=7
SGI_COLOR_GRAY=8
SGI_COLOR_BRIGHT_RED=9
SGI_COLOR_BRIGHT_GREEN=10
SGI_COLOR_BRIGHT_YELLOW=11
SGI_COLOR_BRIGHT_BLUE=12
SGI_COLOR_BRIGHT_MAGENTA=13
SGI_COLOR_BRIGHT_CYAN=14
SGI_COLOR_ORANGE=208

STYLE_WHITE_BRIGHTRED=$CSI$SGI_FOREGC$SGI_COLOR_WHITE";"$SGI_BACKGC$SGI_COLOR_BRIGHT_RED";${SGI_BLINK}m"
STYLE_BRIGHTRED=$CSI$SGI_FOREGC$SGI_COLOR$SGI_COLOR_BRIGHT_RED"m"
STYLE_BRIGHTGREEN=$CSI$SGI_FOREGC$SGI_COLOR_BRIGHT_GREEN"m"
STYLE_WHITE_BRIGHTBLUE=$CSI$SGI_FOREGC$SGI_COLOR_WHITE";"$SGI_BACKGC$SGI_COLOR_BRIGHT_BLUE"m"
STYLE_WHITE_BRIGHTRED=$CSI$SGI_FOREGC$SGI_COLOR_WHITE";"$SGI_BACKGC$SGI_COLOR_BRIGHT_RED"m"

export STYLE_PM25_AQI_GOOD="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;$SGI_BACKGC${SGI_COLOR_BRIGHT_GREEN}m"    #00e400
export STYLE_PM25_AQI_MODERATE="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;$SGI_BACKGC${SGI_COLOR_BRIGHT_YELLOW}m"  #ffff00
export STYLE_PM25_AQI_UNHEALTHY_SENSITIVE="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;$SGI_BACKGC${SGI_COLOR_ORANGE}m"  #ff7e00
export STYLE_PM25_AQI_UNHEALTHY="$CSI$SGI_FOREGC$SGI_COLOR_WHITE;$SGI_BACKGC${SGI_COLOR_BRIGHT_RED}m"     #ff0000
export STYLE_PM25_AQI_VERY_UNHEALTHY="$CSI$SGI_FOREGC$SGI_COLOR_WHITE;$SGI_BACKGC${SGI_COLOR_MAGENTA}m" #99004c
export STYLE_PM25_AQI_HAZARDOUS="$CSI$SGI_FOREGC$SGI_COLOR_WHITE;${SGI_BACKGC}88m" #approximate #88000

export STYLE_UVI_LOW=$STYLE_PM25_AQI_GOOD
export STYLE_UVI_MODERATE=$STYLE_PM25_AQI_MODERATE
export STYLE_UVI_HIGH=$STYLE_PM25_AQI_UNHEALTHY_SENSITIVE
export STYLE_UVI_VERY_HIGH=$STYLE_PM25_AQI_UNHEALTHY
export STYLE_UVI_EXTERME=$STYLE_PM25_AQI_VERY_UNHEALTHY

export STYLE_LIMIT_LIVEDATA=${STYLE_LIMIT_LIVEDATA:=$ANSIESC_SGI_BOLD_INVERT}
export STYLE_LIMIT_LIVEDATA_WINDDAILYMAX=${STYLE_LIMIT_LIVEDATA_WINDDAILYMAX:=$STYLE_WHITE_BRIGHTRED}
export STYLE_LIMIT_LIVEDATA_WINDSPEED=${STYLE_LIMIT_LIVEDATA_WINDSPEED:=$STYLE_WHITE_BRIGHTRED}
export STYLE_LIMIT_LIVEDATA_WINDGUSTSPEED=${STYLE_LIMIT_LIVEDATA_WINDGUSTSPEED:=$STYLE_WHITE_BRIGHTRED}

export STYLE_LIMIT_LIVEDATA_RAINRATE=${STYLE_LIMIT_LIVEDATA_RAINRATE:=$STYLE_WHITE_BRIGHTRED}
export STYLE_LIMIT_LIVEDATA_RAINHOUR=${STYLE_LIMIT_LIVEDATA_RAINHOUR:=$STYLE_WHITE_BRIGHTRED}
export STYLE_LIMIT_LIVEDATA_RAINDAY=${STYLE_LIMIT_LIVEDATA_RAINDAY:=$STYLE_WHITE_BRIGHTRED}
export STYLE_LIMIT_LIVEDATA_RAINEVENT=${STYLE_LIMIT_LIVEDATA_RAINEVENT:=$STYLE_WHITE_BRIGHTRED}

export STYLE_LIMIT_LIVEDATA_OUTTEMP=${STYLE_LIMIT_LIVEDATA_OUTTEMP:=$STYLE_WHITE_BRIGHTBLUE}
export STYLE_LIMIT_LIVEDATA_OUTTEMP_HIGH=${STYLE_LIMIT_LIVEDATA_OUTTEMP_HIGH:=$STYLE_WHITE_BRIGHTRED}
export STYLE_LIMIT_LIVEDATA_INTEMP_LOW=${STYLE_LIMIT_LIVEDATA_INTEMP_LOW:=$STYLE_WHITE_BRIGHTBLUE}
export STYLE_LIMIT_LIVEDATA_INTEMP_HIGH=${STYLE_LIMIT_LIVEDATA_INTEMP_HIGH:=$STYLE_WHITE_BRIGHTRED}

export STYLE_BATTERY_LOW=${STYLE_BATTERY_LOW:=$STYLE_BRIGHTRED}
export STYLE_SIGNAL_LOW=${STYLE_SIGNAL_LOW:=$STYLE_BRIGHTRED}
export STYLE_LEAK=${STYLE_LEAK:="\a"$STYLE_WHITE_BRIGHTRED} # add alert/bell \a if leakage detected

export STYLE_RESET="$ANSIESC_SGI_NORMAL"

export STYLE_HEADER_DEFAULT="$CSI$SGI_BOLD;${SGI_INVERSE}m"
export STYLE_HEADER=${STYLE_HEADER:=$STYLE_HEADER_DEFAULT}

export STYLE_HUMIDITY=${STYLE_HUMIDITY:="$CSI$SGI_FOREGC${SGI_COLOR_BLUE}m"}
export STYLE_HEADER_HUMIDITY=${STYLE_HEADER_HUMIDITY:="$CSI$SGI_BOLD;$SGI_INVERSE;$SGI_FOREGC${SGI_COLOR_BLUE}m"}

export STYLE_HEADER_TEMP=${STYLE_HEADER_TEMP:=$STYLE_HEADER_DEFAULT}
export STYLE_TEMP=${STYLE_TEMP:="$CSI$SGI_FOREGC${SGI_COLOR_BRIGHT_MAGENTA}m"}

export STYLE_HEADER_RAIN=${STYLE_HEADER_RAIN="$CSI$SGI_BOLD;$SGI_INVERSE;$SGI_FOREGC${SGI_COLOR_BRIGHT_BLUE}m"}
export STYLE_RAIN=${STYLE_RAIN:="$CSI$SGI_FOREGC${SGI_COLOR_BRIGHT_BLUE}m"}

export STYLE_SENSOR_DISABLE=${STYLE_SENSOR_DISABLE:=$STYLE_BRIGHTRED}
export STYLE_SENSOR_SEARCH=${STYLE_SENSOR_SEARCH:=$STYLE_BRIGHTGREEN}
