#!/bin/sh

#colors
STYLE_BEUFORT_0="$CSI$SGI_BACKGC$SGI_COLOR_BLACK"m                                          #  0.5 m/s
STYLE_BEUFORT_1="$CSI$SGI_BACKGC$SGI_COLOR_BLUE"m                                           #  1.6 m/s
STYLE_BEUFORT_2="$CSI$SGI_BACKGC$SGI_COLOR_BRIGHT_BLUE"m                                    #  3.4 m/s
STYLE_BEUFORT_3="$CSI$SGI_BACKGC$SGI_COLOR_CYAN"m                                           #  5.5 m/s
STYLE_BEUFORT_4="$CSI$SGI_BACKGC$SGI_COLOR_BRIGHT_CYAN;$SGI_FOREGC${SGI_COLOR_BLACK}m"      #  8.0 m/s
STYLE_BEUFORT_5="$CSI$SGI_BACKGC$SGI_COLOR_GREEN"m                                          # 10.8 m/s
STYLE_BEUFORT_6="$CSI$SGI_BACKGC$SGI_COLOR_BRIGHT_GREEN;$SGI_FOREGC${SGI_COLOR_BLACK}m"     # 13.9 m/s
STYLE_BEUFORT_7="$CSI$SGI_BACKGC$SGI_COLOR_YELLOW;$SGI_FOREGC${SGI_COLOR_BLACK}m"           # 17.2 m/s
STYLE_BEUFORT_8="$CSI$SGI_BACKGC$SGI_COLOR_BRIGHT_YELLOW;$SGI_FOREGC${SGI_COLOR_BLACK}m"    # 20.8 m/s
STYLE_BEUFORT_9="$CSI$SGI_BACKGC$SGI_COLOR_RED"m                                            # 24.5 m/s
STYLE_BEUFORT_10="$CSI$SGI_BACKGC$SGI_COLOR_BRIGHT_RED"m                                    # 28.5 m/s
STYLE_BEUFORT_11="$CSI$SGI_BACKGC$SGI_COLOR_MAGENTA"m                                       # 32.7 m/s
STYLE_BEUFORT_12="$CSI$SGI_BACKGC$SGI_COLOR_BRIGHT_MAGENTA;$SGI_FOREGC${SGI_COLOR_BLACK}m"

#grayscale

#export STYLE_BEUFORT_0="$CSI${SGI_BACKGC}232;$SGI_FOREGC${SGI_COLOR_WHITE}m"
#export STYLE_BEUFORT_1="$CSI${SGI_BACKGC}234;$SGI_FOREGC${SGI_COLOR_WHITE}m"
#export STYLE_BEUFORT_2="$CSI${SGI_BACKGC}236;$SGI_FOREGC${SGI_COLOR_WHITE}m"
#export STYLE_BEUFORT_3="$CSI${SGI_BACKGC}238;$SGI_FOREGC${SGI_COLOR_WHITE}m"
#export STYLE_BEUFORT_4="$CSI${SGI_BACKGC}240;$SGI_FOREGC${SGI_COLOR_WHITE}m"
#export STYLE_BEUFORT_5="$CSI${SGI_BACKGC}242;$SGI_FOREGC${SGI_COLOR_WHITE}m"
#export STYLE_BEUFORT_6="$CSI${SGI_BACKGC}244;$SGI_FOREGC${SGI_COLOR_BLACK}m"
#export STYLE_BEUFORT_7="$CSI${SGI_BACKGC}246;$SGI_FOREGC${SGI_COLOR_BLACK}m"
#export STYLE_BEUFORT_8="$CSI${SGI_BACKGC}248;$SGI_FOREGC${SGI_COLOR_BLACK}m"
#export STYLE_BEUFORT_9="$CSI${SGI_BACKGC}250;$SGI_FOREGC${SGI_COLOR_BLACK}m"
#export STYLE_BEUFORT_10="$CSI${SGI_BACKGC}252;$SGI_FOREGC${SGI_COLOR_BLACK}m"
#export STYLE_BEUFORT_11="$CSI${SGI_BACKGC}254;$SGI_FOREGC${SGI_COLOR_BLACK}m"
#export STYLE_BEUFORT_12="$CSI${SGI_BACKGC}255;$SGI_FOREGC${SGI_COLOR_BLACK}m"

BEUFORT_0=5  #0.5 m/s
BEUFORT_1=16
BEUFORT_2=34
BEUFORT_3=55
BEUFORT_4=80
BEUFORT_5=108
BEUFORT_6=139
BEUFORT_7=172
BEUFORT_8=208
BEUFORT_9=245
BEUFORT_10=285
BEUFORT_11=327

  BEUFORT_0_DESCRIPTION=${BEUFORT_0_DESCRIPTION:="CALM           "}
  BEUFORT_1_DESCRIPTION=${BEUFORT_1_DESCRIPTION:="LIGHT AIR      "}
  BEUFORT_2_DESCRIPTION=${BEUFORT_2_DESCRIPTION:="LIGHT BREEZE   "}
  BEUFORT_3_DESCRIPTION=${BEUFORT_3_DESCRIPTION:="GENTLE BREEZE  "}
  BEUFORT_4_DESCRIPTION=${BEUFORT_4_DESCRIPTION:="MODERATE BREEZE"}
  BEUFORT_5_DESCRIPTION=${BEUFORT_5_DESCRIPTION:="FRESH BREEZE   "}
  BEUFORT_6_DESCRIPTION=${BEUFORT_6_DESCRIPTION:="STRONG BREEZE  "}
  BEUFORT_7_DESCRIPTION=${BEUFORT_7_DESCRIPTION:="NEAR GALE      "}
  BEUFORT_8_DESCRIPTION=${BEUFORT_8_DESCRIPTION:="GALE           "}
  BEUFORT_9_DESCRIPTION=${BEUFORT_9_DESCRIPTION:="STRONG GALE    "}
BEUFORT_10_DESCRIPTION=${BEUFORT_10_DESCRIPTION:="STORM          "}
BEUFORT_11_DESCRIPTION=${BEUFORT_11_DESCRIPTION:="VIOLENT STORM  "}
BEUFORT_12_DESCRIPTION=${BEUFORT_12_DESCRIPTION:="HURRICANE      "}

setBeufort()
{
   if   [ "$1" -lt $BEUFORT_0 ]; then
      VALUE_BEUFORT=0
      VALUE_BEUFORT_DESCRIPTION=$BEUFORT_0_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_1 ]; then
     VALUE_BEUFORT=1
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_1_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_2 ]; then
     VALUE_BEUFORT=2
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_2_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_3 ]; then
     VALUE_BEUFORT=3
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_3_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_4 ]; then
     VALUE_BEUFORT=4
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_4_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_5 ]; then
     VALUE_BEUFORT=5
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_5_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_6 ]; then
     VALUE_BEUFORT=6
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_6_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_7 ]; then
     VALUE_BEUFORT=7
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_7_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_8 ]; then
     VALUE_BEUFORT=8
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_8_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_9 ]; then
     VALUE_BEUFORT=9
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_9_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_10 ]; then
     VALUE_BEUFORT=10
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_10_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_11 ]; then
     VALUE_BEUFORT=11
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_11_DESCRIPTION
   elif [ "$1" -ge $BEUFORT_11 ]; then
     VALUE_BEUFORT=12
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_12_DESCRIPTION
   fi
}

setStyleBeufort()
{
    [ -z "$1" ] && return 1

    if  [ "$1" -lt $BEUFORT_0 ]; then
      STYLE_BEUFORT=$STYLE_BEUFORT_0
   elif [ "$1" -lt $BEUFORT_1 ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_1
   elif [ "$1" -lt $BEUFORT_2 ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_2
   elif [ "$1" -lt $BEUFORT_3 ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_3
   elif [ "$1" -lt $BEUFORT_4 ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_4
   elif [ "$1" -lt $BEUFORT_5 ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_5
   elif [ "$1" -lt $BEUFORT_6 ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_6
   elif [ "$1" -lt $BEUFORT_7 ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_7
   elif [ "$1" -lt $BEUFORT_8 ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_8
   elif [ "$1" -lt $BEUFORT_9 ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_9
   elif [ "$1" -lt $BEUFORT_10 ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_10
   elif [ "$1" -lt $BEUFORT_11 ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_11
   elif [ "$1" -ge $BEUFORT_11 ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_12
   fi
}