#!/bin/sh

#colors
STYLE_BEUFORT_0=""                                                                          #  0.5 m/s
STYLE_BEUFORT_1="$CSI$SGI_BACKGC$SGI_COLOR_BLUE;$SGI_FOREGC${SGI_COLOR_BRIGHT_WHITE}m"      #  1.6 m/s
STYLE_BEUFORT_2="$CSI$SGI_BACKGC$SGI_COLOR_BRIGHT_BLUE"m                                    #  3.4 m/s
STYLE_BEUFORT_3="$CSI$SGI_BACKGC$SGI_COLOR_CYAN"m                                           #  5.5 m/s
STYLE_BEUFORT_4="$CSI$SGI_BACKGC$SGI_COLOR_BRIGHT_CYAN;$SGI_FOREGC${SGI_COLOR_BLACK}m"      #  8.0 m/s
STYLE_BEUFORT_5="$CSI$SGI_BACKGC$SGI_COLOR_GREEN"m                                          # 10.8 m/s
STYLE_BEUFORT_6="$CSI$SGI_BACKGC$SGI_COLOR_BRIGHT_GREEN;$SGI_FOREGC${SGI_COLOR_BLACK}m"     # 13.9 m/s
STYLE_BEUFORT_7="$CSI$SGI_BACKGC$SGI_COLOR_YELLOW;$SGI_FOREGC${SGI_COLOR_BLACK}m"           # 17.2 m/s
STYLE_BEUFORT_8="$CSI$SGI_BACKGC$SGI_COLOR_BRIGHT_YELLOW;$SGI_FOREGC${SGI_COLOR_BLACK}m"    # 20.8 m/s
STYLE_BEUFORT_9="$CSI$SGI_BACKGC$SGI_COLOR_RED"m                                            # 24.5 m/s
STYLE_BEUFORT_10="$CSI$SGI_BACKGC$SGI_COLOR_BRIGHT_RED"m                                    # 28.5 m/s
STYLE_BEUFORT_11="$CSI$SGI_BACKGC$SGI_COLOR_MAGENTA"m                                       # 32.7 m/s
STYLE_BEUFORT_12="$CSI$SGI_BACKGC$SGI_COLOR_BRIGHT_MAGENTA;$SGI_FOREGC${SGI_COLOR_BLACK}m"

#grayscale

#export STYLE_BEUFORT_0="$CSI${SGI_BACKGC}232;$SGI_FOREGC${SGI_COLOR_WHITE}m"
#export STYLE_BEUFORT_1="$CSI${SGI_BACKGC}234;$SGI_FOREGC${SGI_COLOR_WHITE}m"
#export STYLE_BEUFORT_2="$CSI${SGI_BACKGC}236;$SGI_FOREGC${SGI_COLOR_WHITE}m"
#export STYLE_BEUFORT_3="$CSI${SGI_BACKGC}238;$SGI_FOREGC${SGI_COLOR_WHITE}m"
#export STYLE_BEUFORT_4="$CSI${SGI_BACKGC}240;$SGI_FOREGC${SGI_COLOR_WHITE}m"
#export STYLE_BEUFORT_5="$CSI${SGI_BACKGC}242;$SGI_FOREGC${SGI_COLOR_WHITE}m"
#export STYLE_BEUFORT_6="$CSI${SGI_BACKGC}244;$SGI_FOREGC${SGI_COLOR_BLACK}m"
#export STYLE_BEUFORT_7="$CSI${SGI_BACKGC}246;$SGI_FOREGC${SGI_COLOR_BLACK}m"
#export STYLE_BEUFORT_8="$CSI${SGI_BACKGC}248;$SGI_FOREGC${SGI_COLOR_BLACK}m"
#export STYLE_BEUFORT_9="$CSI${SGI_BACKGC}250;$SGI_FOREGC${SGI_COLOR_BLACK}m"
#export STYLE_BEUFORT_10="$CSI${SGI_BACKGC}252;$SGI_FOREGC${SGI_COLOR_BLACK}m"
#export STYLE_BEUFORT_11="$CSI${SGI_BACKGC}254;$SGI_FOREGC${SGI_COLOR_BLACK}m"
#export STYLE_BEUFORT_12="$CSI${SGI_BACKGC}255;$SGI_FOREGC${SGI_COLOR_BLACK}m"

setStyleBeufort()
{
    [ -z "$1" ] && return 1

    if  [ "$1" -lt "$BEUFORT_0" ]; then
      STYLE_BEUFORT=$STYLE_BEUFORT_0
   elif [ "$1" -lt "$BEUFORT_1" ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_1
   elif [ "$1" -lt "$BEUFORT_2" ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_2
   elif [ "$1" -lt "$BEUFORT_3" ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_3
   elif [ "$1" -lt "$BEUFORT_4" ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_4
   elif [ "$1" -lt "$BEUFORT_5" ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_5
   elif [ "$1" -lt "$BEUFORT_6" ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_6
   elif [ "$1" -lt "$BEUFORT_7" ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_7
   elif [ "$1" -lt "$BEUFORT_8" ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_8
   elif [ "$1" -lt "$BEUFORT_9" ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_9
   elif [ "$1" -lt "$BEUFORT_10" ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_10
   elif [ "$1" -lt "$BEUFORT_11" ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_11
   elif [ "$1" -ge "$BEUFORT_11" ]; then
     STYLE_BEUFORT=$STYLE_BEUFORT_12
   fi
}