#!/usr/bin/dash
#Limits for triggering of ansi escape highlights

export LIVEDATA_WINDSPEED_LIMIT=${LIVEDATA_WINDSPEED_LIMIT:=80}  # 8 m/s - set param if value unset/null
export LIVEDATA_WINDGUSTSPEED_LIMIT=${LIVEDATA_WINDGUSTSPEED_LIMIT:=80}  # 8 m/s - set param if value unset/null
export LIVEDATA_WINDDAILYMAX_LIMIT=${LIVEDATA_WINDDAILYMAX_LIMIT:=80}  # 8 m/s - set param if value unset/null

export LIVEDATA_RAINRATE_LIMIT=${LIVEDATA_RAINRATE_LIMIT:=5} # 0.5 mm/h - scale x10
export LIVEDATA_RAINHOUR_LIMIT=${LIVEDATA_RAINHOUR_LIMIT:=5}
export LIVEDATA_RAINDAY_LIMIT=${LIMIT_LIVEDATA_RAINDAILY:=100} # 10.0 mm
export LIVEDATA_RAINEVENT_LIMIT=${LIVEDATA_RAINEVENT_LIMIT:=200}

export LIVEDATA_RELBARO_LIMIT_LOW=${LIMIT_LIVEDATA_RELBARO_LOW:=9900} # 990 hpa - scale x10
export LIVEDATA_ABSBARO_LIMIT_LOW=${LIMIT_LIVEDATA_ABSBARO_LOW:=9900} 

export LIVEDATA_OUTTEMP_LIMIT_LOW=${LIVEDATA_OUTTEMP_LIMIT_LOW:=-10} # -1.0 - scale x10
export LIVEDATA_OUTTEMP_LIMIT_HIGH=${LIVEDATA_OUTTEMP_LIMIT_HIGH:=170} # 17.0 - scale x10
export LIVEDATA_INTEMP_LIMIT_LOW=${LIVEDATA_INTEMP_LIMIT_LOW:=200} 
export LIVEDATA_INTEMP_LIMIT_HIGH=${LIVEDATA_INTEMP_LIMIT_HIGH:=230} 
