#!/bin/sh
#export STYLE_PM25_AQI_GOOD="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;$SGI_BACKGC${SGI_COLOR_BRIGHT_GREEN}m"    #00e400
#export STYLE_PM25_AQI_MODERATE="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;$SGI_BACKGC${SGI_COLOR_BRIGHT_YELLOW}m"  #ffff00
#export STYLE_PM25_AQI_UNHEALTHY_SENSITIVE="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;$SGI_BACKGC${SGI_COLOR_ORANGE}m"  #ff7e00
#export STYLE_PM25_AQI_UNHEALTHY="$CSI$SGI_FOREGC$SGI_COLOR_WHITE;$SGI_BACKGC${SGI_COLOR_BRIGHT_RED}m"     #ff0000
#export STYLE_PM25_AQI_VERY_UNHEALTHY="$CSI$SGI_FOREGC$SGI_COLOR_WHITE;$SGI_BACKGC${SGI_COLOR_MAGENTA}m" #99004c
#export STYLE_PM25_AQI_HAZARDOUS="$CSI$SGI_FOREGC$SGI_COLOR_WHITE;${SGI_BACKGC}88m" #approximate #88000

#standard colors, comability with watch --color command - watch from procps-ng 3.3.16
#[38;5;?m [48;5;?M does not work
export STYLE_PM25_AQI_GOOD="$CSI${SGI_FOREGC_BLACK}m$CSI${SGI_BACKGC_GREEN}m"  
export STYLE_PM25_AQI_MODERATE="$CSI${SGI_FOREGC_BLACK}m$CSI${SGI_BACKGC_YELLOW}m" 
export STYLE_PM25_AQI_UNHEALTHY_SENSITIVE="$CSI${SGI_FOREGC_BLACK}m${CSI}${SGI_BACKGC_BLUE}m"
export STYLE_PM25_AQI_UNHEALTHY="$CSI${SGI_FOREGC_BLACK}m${CSI}${SGI_BACKGC_RED}m"
export STYLE_PM25_AQI_VERY_UNHEALTHY="$CSI${SGI_FOREGC_BLACK}m${CSI}${SGI_BACKGC_MAGENTA}m"
export STYLE_PM25_AQI_HAZARDOUS="$CSI${SGI_FOREGC_BLACK}m${CSI}${SGI_BACKGC_CYAN}m"

setStyleAQI()
{
    [ -z "$1" ] && return 1
    
    if [ "$1" -lt 121 ]; then
       STYLE_AQI="$STYLE_PM25_AQI_GOOD"
    elif [ "$1" -ge 121 ] && [ "$1" -lt "$PM25_AQI_MODERATE_LIMIT" ]; then
        STYLE_AQI=$STYLE_PM25_AQI_MODERATE
    elif [ "$1" -ge "$PM25_AQI_MODERATE_LIMIT" ] && [ "$1" -lt "$PM25_AQI_UNHEALTHY_SENSITIVE_LIMIT" ]; then
        STYLE_AQI=$STYLE_PM25_AQI_UNHEALTHY_SENSITIVE
    elif [ "$1" -ge "$PM25_AQI_UNHEALTHY_SENSITIVE_LIMIT" ] && [ "$1" -lt "$PM25_AQI_UNHEALTHY_LIMIT" ]; then
        STYLE_AQI=$STYLE_PM25_AQI_UNHEALTHY
    elif [ "$1" -ge "$PM25_AQI_UNHEALTHY_LIMIT" ] && [ "$1" -lt "$PM25_AQI_VERY_UNHEALTHY_LIMIT" ]; then
        STYLE_AQI=$STYLE_PM25_AQI_VERY_UNHEALTHY
    elif [ "$1" -ge "$PM25_AQI_VERY_UNHEALTHY_LIMIT" ]; then
       #STYLE_AQI="$CSI$SGI_FOREGC$SGI_COLOR_WHITE;${SGI_BACKGC_24BIT}126;0;35m" #7f0023
       STYLE_AQI=$STYLE_PM25_AQI_HAZARDOUS
    fi
}