#!/bin/sh
export STYLE_RAININTENSITY_LIGHT="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;$SGI_BACKGC${SGI_COLOR_BRIGHT_CYAN}m"    #00e400
export STYLE_RAININTENSITY_MODERATE="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;$SGI_BACKGC${SGI_COLOR_BRIGHT_YELLOW}m"  #ffff00
export STYLE_RAININTENSITY_HEAVY="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;$SGI_BACKGC${SGI_COLOR_ORANGE}m"  #ff7e00
export STYLE_RAININTENSITY_EXTREME="$CSI$SGI_FOREGC$SGI_COLOR_WHITE;$SGI_BACKGC${SGI_COLOR_BRIGHT_RED}m"     #ff0000

#yr.no - chrome color picker/devtools
#export STYLE_RAININTENSITY_LIGHT="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;${SGI_BACKGC24}145;228;255m"
#export STYLE_RAININTENSITY_MODERATE="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;${SGI_BACKGC24}0;170;255m"
#export STYLE_RAININTENSITY_HEAVY="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;${SGI_BACKGC24}0;128;255m"
#export STYLE_RAININTENSITY_EXTREME="$CSI$SGI_FOREGC$SGI_COLOR_WHITE;${SGI_BACKGC24}122;0;135m"