#!/bin/sh
export STYLE_RAININTENSITY_LIGHT="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;$SGI_BACKGC${SGI_COLOR_BRIGHT_CYAN}m"    #00e400
export STYLE_RAININTENSITY_MODERATE="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;$SGI_BACKGC${SGI_COLOR_BRIGHT_YELLOW}m"  #ffff00
export STYLE_RAININTENSITY_HEAVY="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;$SGI_BACKGC${SGI_COLOR_ORANGE}m"  #ff7e00
export STYLE_RAININTENSITY_EXTREME="$CSI$SGI_FOREGC$SGI_COLOR_WHITE;$SGI_BACKGC${SGI_COLOR_BRIGHT_RED}m"     #ff0000

#yr.no - chrome color picker/devtools
#export STYLE_RAININTENSITY_LIGHT="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;${SGI_BACKGC24}145;228;255m"
#export STYLE_RAININTENSITY_MODERATE="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;${SGI_BACKGC24}0;170;255m"
#export STYLE_RAININTENSITY_HEAVY="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;${SGI_BACKGC24}0;128;255m"
#export STYLE_RAININTENSITY_EXTREME="$CSI$SGI_FOREGC$SGI_COLOR_WHITE;${SGI_BACKGC24}122;0;135m"

#https://en.wikipedia.org/wiki/Rain#Intensity
        RAININTENSITY_ZERO=${RAININTENSITY_ZERO:=""} #clear
      RAININTENSITY_LIGHT=${RAININTENSITY_LIGHT:="LIGHT"}
RAININTENSITY_MODERATE=${RAININTENSITY_MODERATE:="MODERATE"}
      RAININTENSITY_HEAVY=${RAININTENSITY_HEAVY:="HEAVY"}
  RAININTENSITY_EXTREME=${RAININTENSITY_EXTREME:="EXTREME"}

  RAININTENSITY_LIGHT_LIMIT=${RAININTENSITY_LIGHT_LIMIT:=25}
  RAININTENSITY_MODERATE_LIMIT=${RAINTENSITY_MODERATE_LIMIT:=76}
  RAININTENSITY_HEAVY_LIMIT=${RAINTENSITY_HEAVY_LIMIT:=500}

setRainIntensity()
# $1 rainintensity (scale 10)
# set VALUE_RAININTENSITY
{
    if [ "$1" -eq 0 ]; then
      VALUE_RAININTENSITY=$RAININTENSITY_ZERO
    elif [ "$1" -gt 0 ] &&  [ "$1" -lt $RAININTENSITY_LIGHT_LIMIT ]; then
      VALUE_RAININTENSITY=$RAININTENSITY_LIGHT
    elif [ "$1" -ge $RAININTENSITY_LIGHT_LIMIT ] && [ "$1" -lt $RAININTENSITY_MODERATE_LIMIT ]; then
      VALUE_RAININTENSITY=$RAININTENSITY_MODERATE
    elif [ "$1" -ge  $RAININTENSITY_MODERATE_LIMIT ] && [ "$1" -lt $RAININTENSITY_HEAVY_LIMIT ]; then
      VALUE_RAININTENSITY=$RAININTENSITY_HEAVY
    elif [ "$1" -gt $RAININTENSITY_HEAVY_LIMIT ]; then
      VALUE_RAININTENSITY=$RAININTENSITY_EXTREME
    fi
}

setStyleRainIntensity()
{
    if [ "$1" -eq 0 ]; then
       unset STYLE_RAININTENSITY
    elif [ "$1" -gt 0 ] && [ "$1" -lt "$RAININTENSITY_LIGHT_LIMIT" ]; then
       STYLE_RAININTENSITY="$STYLE_RAININTENSITY_LIGHT"
    elif [ "$1" -ge $RAININTENSITY_LIGHT_LIMIT ] && [ "$1" -lt $RAININTENSITY_MODERATE_LIMIT ]; then
        STYLE_RAININTENSITY=$STYLE_RAININTENSITY_MODERATE
    elif [ "$1" -ge $RAININTENSITY_MODERATE_LIMIT ] && [ "$1" -lt $RAININTENSITY_HEAVY_LIMIT ]; then
        STYLE_RAININTENSITY=$STYLE_RAININTENSITY_HEAVY
    elif [ "$1" -ge $RAININTENSITY_HEAVY_LIMIT ]; then
        STYLE_RAININTENSITY=$STYLE_RAININTENSITY_EXTREME
    fi
}