#!/bin/sh
export STYLE_UVI_LOW="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;$SGI_BACKGC${SGI_COLOR_BRIGHT_GREEN}m"
export STYLE_UVI_MODERATE="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;$SGI_BACKGC${SGI_COLOR_BRIGHT_YELLOW}m"
export STYLE_UVI_HIGH="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;$SGI_BACKGC$SGI_BACKGC${SGI_COLOR_ORANGE}m"
export STYLE_UVI_VERY_HIGH="$CSI$SGI_FOREGC$SGI_COLOR_BLACK;$SGI_BACKGC${SGI_COLOR_BRIGHT_RED}m"
export STYLE_UVI_EXTERME="$CSI$SGI_BACKGC$SGI_COLOR_BLACK;$SGI_BACKGC${SGI_COLOR_MAGENTA}m"
