#!/bin/sh
#shellcheck disable=SC2034
BEUFORT_0=5  #0.5 m/s
BEUFORT_1=16
BEUFORT_2=34
BEUFORT_3=55
BEUFORT_4=80
BEUFORT_5=108
BEUFORT_6=139
BEUFORT_7=172
BEUFORT_8=208
BEUFORT_9=245
BEUFORT_10=285
BEUFORT_11=327

  BEUFORT_0_DESCRIPTION=${BEUFORT_0_DESCRIPTION:="CALM"}
  BEUFORT_1_DESCRIPTION=${BEUFORT_1_DESCRIPTION:="LIGHT AIR"}
  BEUFORT_2_DESCRIPTION=${BEUFORT_2_DESCRIPTION:="LIGHT BREEZE"}
  BEUFORT_3_DESCRIPTION=${BEUFORT_3_DESCRIPTION:="GENTLE BREEZE"}
  BEUFORT_4_DESCRIPTION=${BEUFORT_4_DESCRIPTION:="MODERATE BREEZE"}
  BEUFORT_5_DESCRIPTION=${BEUFORT_5_DESCRIPTION:="FRESH BREEZE"}
  BEUFORT_6_DESCRIPTION=${BEUFORT_6_DESCRIPTION:="STRONG BREEZE"}
  BEUFORT_7_DESCRIPTION=${BEUFORT_7_DESCRIPTION:="NEAR GALE"}
  BEUFORT_8_DESCRIPTION=${BEUFORT_8_DESCRIPTION:="GALE"}
  BEUFORT_9_DESCRIPTION=${BEUFORT_9_DESCRIPTION:="STRONG GALE"}
BEUFORT_10_DESCRIPTION=${BEUFORT_10_DESCRIPTION:="STORM"}
BEUFORT_11_DESCRIPTION=${BEUFORT_11_DESCRIPTION:="VIOLENT STORM"}
BEUFORT_12_DESCRIPTION=${BEUFORT_12_DESCRIPTION:="HURRICANE"}

setBeufort()
{
   if   [ "$1" -lt $BEUFORT_0 ]; then
      VALUE_BEUFORT=0
      VALUE_BEUFORT_DESCRIPTION=$BEUFORT_0_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_1 ]; then
     VALUE_BEUFORT=1
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_1_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_2 ]; then
     VALUE_BEUFORT=2
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_2_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_3 ]; then
     VALUE_BEUFORT=3
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_3_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_4 ]; then
     VALUE_BEUFORT=4
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_4_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_5 ]; then
     VALUE_BEUFORT=5
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_5_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_6 ]; then
     VALUE_BEUFORT=6
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_6_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_7 ]; then
     VALUE_BEUFORT=7
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_7_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_8 ]; then
     VALUE_BEUFORT=8
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_8_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_9 ]; then
     VALUE_BEUFORT=9
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_9_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_10 ]; then
     VALUE_BEUFORT=10
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_10_DESCRIPTION
   elif [ "$1" -lt $BEUFORT_11 ]; then
     VALUE_BEUFORT=11
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_11_DESCRIPTION
   elif [ "$1" -ge $BEUFORT_11 ]; then
     VALUE_BEUFORT=12
     VALUE_BEUFORT_DESCRIPTION=$BEUFORT_12_DESCRIPTION
   fi
}
