#!/bin/sh

# https://www.airnow.gov/aqi/aqi-basics/
                              PM25_AQI_GOOD=${PM25_AQI_GOOD:="GOOD"}
                      PM25_AQI_MODERATE=${PM25_AQI_MODERATE:="MODERATE"}
PM25_AQI_UNHEALTHY_SENSITIVE=${PM25_AQI_UNHEALTHY_SENSITIVE:="UNHEALTHY S."}
                    PM25_AQI_UNHEALTHY=${PM25_AQI_UNHEALTHY:="UNHEALTY"}
          PM25_AQI_VERY_UNHEALTHY=${PM25_AQI_VERY_UNHEALTHY:="VERY UNHEALTY"}
                    PM25_AQI_HAZARDOUS=${PM25_AQI_HAZARDOUS:="HAZARDOUS"}

               PM25_AQI_GOOD_LIMIT=121
           PM25_AQI_MODERATE_LIMIT=355
PM25_AQI_UNHEALTHY_SENSITIVE_LIMIT=555
         PM25_AQI_UNHEALTHY_LIMIT=1505
    PM25_AQI_VERY_UNHEALTHY_LIMIT=2505

setAQI()
#https://blissair.com/what-is-pm-2-5.htm
{
    [ -z "$1" ] && return 1

    if [ "$1" -lt $PM25_AQI_GOOD_LIMIT ]; then
      VALUE_PM25_AQI=$PM25_AQI_GOOD
    elif [ "$1" -ge $PM25_AQI_GOOD_LIMIT ] && [ "$1" -lt $PM25_AQI_MODERATE_LIMIT ]; then
      VALUE_PM25_AQI=$PM25_AQI_MODERATE
    elif [ "$1" -ge $PM25_AQI_MODERATE_LIMIT ] && [ "$1" -lt $PM25_AQI_UNHEALTHY_SENSITIVE_LIMIT ]; then
      VALUE_PM25_AQI=$PM25_AQI_UNHEALTHY_SENSITIVE
    elif [ "$1" -ge $PM25_AQI_UNHEALTHY_SENSITIVE_LIMIT ] && [ "$1" -lt $PM25_AQI_UNHEALTHY_LIMIT ]; then
      VALUE_PM25_AQI=$PM25_AQI_UNHEALTHY
    elif [ "$1" -ge $PM25_AQI_UNHEALTHY_LIMIT ] && [ "$1" -lt $PM25_AQI_VERY_UNHEALTHY_LIMIT ]; then
      VALUE_PM25_AQI=$PM25_AQI_VERY_UNHEALTHY
    elif [ "$1" -ge $PM25_AQI_VERY_UNHEALTHY_LIMIT ]; then
      VALUE_PM25_AQI=$PM25_AQI_HAZARDOUS
    fi
}