#!/bin/sh
WEATHERSERVICEHEADER_ECOWITT_INTERVAL=${WEATHERSERVICEHEADER_ECOWITT_INTERVAL:='ecowitt interval'}
WEATHERSERVICEHEADER_WUNDERGROUND_ID=${WEATHERSERVICEHEADER_WUNDERGROUND_ID:='wunderground id'}
WEATHERSERVICEHEADER_WUNDERGROUND_PASSWORD=${WEATHERSERVICEHEADER_WUNDERGROUND_PASSWORD:='wunderground password'}
WEATHERSERVICEHEADER_WEATHERCLOUD_ID=${WEATHERSERVICEHEADER_WEATHERCLOUD_ID:='weathercloud id'}
WEATHERSERVICEHEADER_WEATHERCLOUD_PASSWORD=${WEATHERSERVICEHEADER_WEATHERCLOUD_PASSWORD:='weathercloud password'}
WEATHERSERVICEHEADER_WOW_ID=${WEATHERSERVICEHEADER_WOW_ID:='weather observations website id'}
WEATHERSERVICEHEADER_WOW_PASSWORD=${WEATHERSERVICEHEADER_WOW_PASSWORD:='weather observations website password'}
WEATHERSERVICEHEADER_CUSTOMIZED_ID=${WEATHERSERVICEHEADER_CUSTOMIZED_ID:='customized wunderground id'}
WEATHERSERVICEHEADER_CUSTOMIZED_PASSWORD=${WEATHERSERVICEHEADER_CUSTOMIZED_PASSWORD:='customized wunderground password'}
WEATHERSERVICEHEADER_CUSTOMIZED_SERVER=${WEATHERSERVICEHEADER_CUSTOMIZED_SERVER:='customized server'}
WEATHERSERVICEHEADER_CUSTOMIZED_PORT=${WEATHERSERVICEHEADER_CUSTOMIZED_PORT:='customized port'}
WEATHERSERVICEHEADER_CUSTOMIZED_INTERVAL=${WEATHERSERVICEHEADER_CUSTOMIZED_INTERVAL:='customized interval'}

WEATHERSERVICEHEADER_CUSTOMIZED_HTTP=${WEATHERSERVICEHEADER_CUSTOMIZED_HTTP:='customized http protocol'}
WEATHERSERVICEHEADER_CUSTOMIZED_ENABLED=${WEATHERSERVICEHEADER_CUSTOMIZED_ENABLED:='customized enabled'}
WEATHERSERVICEHEADER_CUSTOMIZED_PATH_ECOWITT=${WEATHERSERVICEHEADER_CUSTOMIZED_PATH_ECOWITT:='customized path ecowitt'}
WEATHERSERVICEHEADER_CUSTOMIZED_PATH_WUNDERGROUND=${WEATHERSERVICEHEADER_CUSTOMIZED_PATH_WUNDERGROUND:='customized path wunderground'}

WEATHERSERVICEHEADERUNIT_MINUTE=${WEATHERSERVICEHEADERUNIT_MINUTE:="minute"}
WEATHERSERVICEHEADERUNIT_MINUTES=${WEATHERSERVICEHEADERUNIT_MINUTES:="minutes"}
WEATHERSERVICEHEADERUNIT_SECONDS=${WEATHERSERVICEHEADERUNIT_SECONDS:="seconds"}
