#!/bin/sh
export TEST=test
 export LIVEDATA_INTEMP_RAW LIVEDATA_INTEMP LIVEDATA_INHUMI\
           LIVEDATA_ABSBARO_RAW LIVEDATA_ABSBARO_RAW LIVEDATA_RELBARO_RAW LIVEDATA_RELBARO\
           LIVEDATA_OUTTEMP_RAW LIVEDATA_OUTTEMP
LIVEDATA_OUTTEMP=3
./test-view.sh
echo Finish