#!/usr/bin/bash 
 checksumnew ()
#$1 - packet body string (after ff ff header), format ff ff 50 00 .. .. .. {checksum}
{
  typeset buffer 2>/dev/null || local buffer
  typeset checksum 2>/dev/null || local checksum
  buffer=$1
  read -r B1 buffer << EOB
$buffer
EOB
>&2 echo "read $B1"
 checksum=$(( 0x$B1 ))

  while [ -n "$buffer" ]; do 
    read -r B1 buffer << EOB
$buffer
EOB
>&2 echo "read $B1"
    checksum=$(( ( checksum + 0x$B1 ) & 0xff ))
  done

  >&2 echo "checksum $checksum"
}

checksumnew "50 01 02 03"