#!/bin/sh
LOG_CSV="$(date -u +"%F %T")"
[ -n "$LIVEDATA_OUTTEMP" ] && [ -n "$LIVEDATA_OUTHUMI" ] && LOG_CSV="$LOG_CSV,$LIVEDATA_OUTTEMP,$LIVEDATA_OUTHUMI"
LOG_CMD="$LOG_CMD,$LIVEDATA_INTEMP,$LIVEDATA_INHUMI,$LIVEDATA_PRESSURE_RELBARO"

if [ -n "$LIVEDATA_WINDSPEED" ]; then # assumes other variables are set
    LOG_CSV="$LOG_CSV,$LIVEDATA_WINDDIRECTION_UINT16,$LIVEDATA_WINDDIRECTION_COMPASS,$LIVEDATA_WINDSPEED,$LIVEDATA_WINDGUSTSPEED"
fi

if [ -n "$LIVEDATA_SOLAR_LIGHT" ]; then
    LOG_CSV="$LOG_CSV,$LIVEDATA_SOLAR_LIGHT,$LIVEDATA_SOLARRADIATION,$LIVEDATA_SOLAR_UVI"
fi

if [ -n "$LIVEDATA_RAINRATE" ]; then 
    LOG_CSV="$LOG_CSV,$LIVEDATA_RAINRATE,$LIVEDATA_RAINDAY,$LIVEDATA_RAINWEEK,$LIVEDATA_RAINMONTH,$LIVEDATA_RAINYEAR"
fi

echo "$LOG_CSV"
